.gitignore, composer.json, inc/pantheon-updates.php
Fixes #12
When using a development/pre-release version of WordPress, WordPress notifies the user that an update is available. While this might be _technically true_ -- development versions always have a newer version available if you're on the nightly channel -- the message that says to apply those updates in the Pantheon dashboard is not.
In fact, we _don't_ want people to be applying (or attempt to apply) WordPress updates in the Pantheon dashboard if they're using development versions -- if an update ever showed up there, it would overwrite the development version of  WordPress that was installed.
This PR addresses the issue by displaying a unique message if a user is running a development version of WordPress. 
This PR also adds our WP Coding Standards so the refactored …
=> [BUGS-6017] Update the WP update messaging for development versions

inc/pantheon-multisite-finalize.php, pantheon.php
=> Detects if a user is using the correct upstream and framework and give them appropriate next steps to finalize WPMS setup.

inc/pantheon-multisite-finalize.php, pantheon.php
Sites with `define('WP_ALLOW_MULTISITE', false);` are erroneously getting prompted to fix their upstream, as we we only check `WP_ALLOW_MULTISITE` was set, not its value.
Further consolidated the logic given we were checking both WP_ALLOW_MULTISITE and MULTISITE back-to-back
=> [BUGS-6657] Handle explicit WP_ALLOW_MULTISITE false correctly

.gitattributes, .github/workflows/lint.yml, .phpcs.xml, CONTRIBUTING.md, composer.json, inc/cli.php, inc/network/includes-network.php, inc/network/network.php, inc/pantheon-login-form-mods.php, inc/pantheon-multisite-finalize.php, inc/pantheon-network-setup.php, inc/pantheon-page-cache.php, inc/pantheon-plugin-install-notice.php, inc/pantheon-updates.php, pantheon.php
* Updates Pantheon Mu Plugin to use Pantheon WP Coding Standards 2.0
* Fixes all the linting issues highlighted by the updated coding standards
* Adds a PANTHEON_MU_PLUGIN_VERSION constant and actually updates the mu-plugin version (which hasn't been done at all since it was added afaict)
**Todo**
=> [CMSP-669] Update pantheon wp coding standards

.phpcs.xml, bin/phpunit-test.sh, tests/phpunit/test-pantheon-updates.php
This pull request updates the WP version handling and testing in the codebase. It includes the following changes:
- Copies the `wp-latest.json` file from the `tmp` directory into the `tests` directory. This allows us to validate against the version of WP that WP is reporting for itself and remove the hard-coded versions.
- Adds a helper method that gets the WP version from `wp-latest.json`.
- Uses the version stored in `wp-latest.json` for testing.
These changes improve the accuracy and flexibility of WP version handling in the codebase.
This will fix the currently failing tests.
=> Remove hard-coded WP latest version check

inc/functions.php, inc/pantheon-updates.php, pantheon.php, tests/phpunit/test-main.php, tests/phpunit/test-pantheon-updates.php
This moves the `_pantheon_get_current_wordpress_version` out of `pantheon-updates.php` and into a new file that is required for all Pantheon sites. Tests have been updated to reflect the move.
This also bumps the mu plugin version which wasn't done before the last release.
Fixes #30
=> [BUGS-7497] fix wp version checker

inc/fonts.php, tests/phpunit/test-fonts.php
Given that it seems like fonts are considered to be more like media files than themes or plugins, it would be undesirable to commit fonts to the repository, so we don't need our override to the WordPress core behavior.
This PR removes the override.  
See https://github.com/pantheon-systems/documentation/pull/8867
Follows #29.
=> [CMSP-695] Remove override for `font_dir` filter

inc/fonts.php
Per https://github.com/WordPress/gutenberg/pull/58839 the issue causing the infinite loop when `upload_dir` is used inside `font_dir` should be addressed.
This change removes our workaround for that issue and uses `wp_get_upload_dir` directly in the `font_dir` folder.
**Note:** While these changes have been merged into Gutenberg, they have not yet been merged into core or made part of the latest Gutenberg release. This should not be merged until this can be tested and confirmed working (PHP Unit tests are not sufficient).
**Todo:**
=> [CMSP-899] Remove our global for the `upload_dir` infinite loop

LICENSE, README.md, pantheon.php
This PR updates the README so it's more usable and explains what the mu-plugin does better. It also adds a license and some badges to the readme.
=> Repository hygene

README.md, inc/pantheon-page-cache.php, pantheon.php, tests/phpunit/test-page-cache.php
Updates the default cache TTL and adds a new `pantheon_cache_default_ttl` filter.
Adds documentation for the filter (and all the other hooks in the mu-plugin) to the README.md file.
Updates tests with new TTL value as well as adds tests for the filter.
Adds functionality that disables the input value if the filter is used.
Using the default value:
Using the filter:
=> [CMSP-991 CMSP-993] Bump default cache TTL and add filter

inc/site-health.php, pantheon.php, tests/phpunit/test-site-health.php
This PR makes two fundamental changes to the Site Health page:
1. It removes warnings/tests that are not useful on Pantheon's environment. Specifically, it removes tests for a writeable `/wp-content/update` folder, background updates (WP automatic updates) and "available disk space" checks (which are also affected by a read-only file system.
2. It adds a new test for object cache. If Redis is active and an object cache plugin (we recommend) is active, it will inform the user (OCP is preferred, WP Redis recommends OCP), if Redis is not active on the site it will warn and if Redis is active but neither of those plugins are active it will also warn.
**Redis is not active for the site**
**Redis is active but WP-Redis or Object Cache Pro are not active**
**Redis is active and WP-Redis is …
=> [BUGS-6639] site health checks

README.md, inc/pantheon-page-cache.php, tests/phpunit/test-page-cache.php
Replaces all references to "TTL" with "max-age" including in the new filter name.
See https://github.com/pantheon-systems/documentation/pull/8953#discussion_r1578171763
=> [CMSP-1056] TTL to max-age

inc/network/includes-network.php
This PR updates the network setup instructions to use the `PANTHEON_HOSTNAME` constant added in https://github.com/pantheon-systems/WordPress/pull/381 and https://github.com/pantheon-systems/wordpress-composer-managed/pull/119.
=> [BUGS-7678] update multisite install instructions to use `PANTHEON_HOSTNAME` constant

inc/pantheon-page-cache.php
This PR increases the size of the Default Max Age input box (which currently cuts off the last character when greater than 5 characters.
=> [CMSP-995 CMSP-992] make the default cache input box bigger

inc/pantheon-page-cache.php, tests/phpunit/test-page-cache.php
_Reported in community Slack by @brianperondi_
Filtered cache max-age values update in the admin and everywhere _except_ in the cache control header that is sent. 
This PR adds the filter to the value saved in `get_cache_control_header_value` which determines the value sent to the cache-control header.
=> [BUGS-8085] Use filtered value when sending cache control headers

inc/network/includes-network.php, pantheon.php
This pull request fixes the network setup process by requiring the network setup file anytime allow multisite is true. Previously this was only included if MULTISITE was also true, but this prevents our network setup page (with the filters we've added) from displaying on the Network Setup page.
It also removes the tab before ob_start to fix the indentation in the textarea. 
Additionally, it reduces the number of lines in the textarea and uses `wp_kses_post` instead of `esc_html` to prevent escaping legitimate HTML.
=> [CMSP-150] Update network setup

inc/network/includes-network.php, pantheon.php, tests/phpunit/test-network.php
This PR adds a new function that just returns a warning that appears on the Network Setup page in subdirectory multisite installs when the wp-content directory is modified (e.g. as it is in Bedrock). It then implements a filter to disable the warning that WordPress (Composer Managed) can consume (see https://github.com/pantheon-systems/wordpress-composer-managed/pull/144).
A test has been added to validate the output of the new function both before and after the filter has been applied.
=> [SITE-372] allow subdirectory networks warning to be filtered

.github/workflows/lint.yml
This pull request updates the lint workflow to run PHPCBF on pull requests and commit any changes back to the PR before running lint. It also switches the action to run on pull requests instead of on every push so we can pull details from the GH API to inform the PR comment.
=> Add PHPCBF to lint workflow

inc/site-health.php, tests/phpunit/test-compatibility-layer.php
This PR adds the PhastPress plugin to the list of incompatible plugins (see [docs page](https://docs.pantheon.io/plugins-known-issues#phastpress)).
In addition to adding it to the items requireing _review_ (which lists partially and incompatible plugins), it updates the  main site health page to add any plugins that are _incompatible_ on Pantheon to the _critical_ issue section rather than listing them as _recommended improvements_ only.
This is accomplished by adding a new boolean parameter to the `output_compatibility_status_table` function that allows a list of plugins to be passed (e.g. from `get_compatibility_manual_fixes` / `get_compatibility_review_fiexes`) and specifically filter by an `incompatible` value in a new `plugin_compatibility` parameter that can be added to plugins when …
=> Add PhastPress as an incompatible plugin

inc/network/includes-network.php
This pull request adds the `PATH_CURRENT_SITE` constant to the multisite setup instructions. This constant is set to `'/'` and is used to define the current site's path.
Fixes #54
=> Add PATH_CURRENT_SITE to multisite setup instructions

inc/network/includes-network.php, inc/site-health.php
This pull request allows the happy publishing line to be filtered so that it can refer to any line at the end of the file.
Additionally, it removes a redundant variable definition for the WP config file name and makes the location of WP config file filterable.
fixes #55
=> Allow the "happy publishing" line in the network config to be filtered

inc/pantheon-network-setup.php
Skip adding our custom network setup page if multisite has already been configured (MULTISITE constant is true).
=> [BUGS-9130] Don't add network setup if network already setup

.github/workflows/lint.yml
this PR fixes the failing PHPCBF step in the lint workflow which is failing because we're missing the `env` part of the GH environment variable.
=> fix broken linting

inc/site-health.php
Improves the plugin compatibility check by simplifying the conditional logic and ensuring a default state is defined. This change enhances readability and reliability of the compatibility status table and fixes the undefined array key error.
fixes #78
=> Fix plugin compatibility check logic

inc/compatibility/fixes/class-wprocketfix.php
This PR adds an empty remove method. We're not removing anything, so we don't need to do anything. Currently the WPRocket class inside the MU Plugin compatibility layer references the `remove()` method so if you deactivate the plugin and it tries to remove any fixes, the deactivation breaks.
=> Fix WPRocket deactivation hook

.github/workflows/lint.yml, inc/compatibility/class-compatibilityfactory.php
This PR adds a new method hooked to `muplugins_loaded` (which is the first action hook fired by WP and is before `plugins_loaded`) and hooks the `DefineConstantFix` fixes to that (rather than when all the other fixes are applied, e.g. `plugins_loaded`).
fixes #82 (hopefully)
=> Hook constants fixes to an earlier hook than `plugins_loaded`

README.md, inc/compatibility/class-acceleratedmobilepages.php, inc/compatibility/class-auth0.php, inc/compatibility/class-autoptimize.php, inc/compatibility/class-bettersearchreplace.php, inc/compatibility/class-brokenlinkchecker.php, inc/compatibility/class-contactformseven.php, inc/compatibility/class-eventespresso.php, inc/compatibility/class-fastvelocityminify.php, inc/compatibility/class-forcelogin.php, inc/compatibility/class-officialfacebookpixel.php, inc/compatibility/class-polylang.php, inc/compatibility/class-redirection.php, inc/compatibility/class-sliderrevolution.php, inc/compatibility/class-tweetoldpost.php, inc/compatibility/class-woozone.php, inc/compatibility/class-wprocket.php, inc/compatibility/class-yithwoocommerce.php, inc/compatibility/fixes/class-acceleratedmobilepagesfix.php, inc/compatibility/fixes/class-auth0fix.php, inc/compatibility/fixes/class-autoptimizefix.php, inc/compatibility/fixes/class-sliderrevolutionfix.php, inc/compatibility/fixes/class-wprocketfix.php, inc/compatibility/fixes/class-yithchangepdflocationfix.php, inc/site-health.php
relates to https://github.com/pantheon-systems/documentation/pull/9433
fixes #79
=> updates all references to `/plugins-known-issues` with `/wordpress-known-issues`

CONTRIBUTING.md
This PR adds a new section in CONTRIBUTING.md that outlines the two primary methods for contributing to the plugin's compatibility layer:
- Reporting issues for manual fixes via the Site Health tool.
- Implementing automated code fixes using Compatibility and Fix classes.
This provides clear guidance for developers looking to help improve plugin compatibility on the Pantheon platform.
This will hopefullyl make it easier for our future selves to add things to the compatibility layer.
=> docs: add contribution guide for the compatibility layer

.github/workflows/test.yml, composer.json, inc/functions.php, inc/pantheon-updates.php, inc/site-health.php, pantheon.php, phpcs.xml, tests/phpunit/test-site-health.php
Enhance the Site Health page to not display any report if user is on a Basic plan where Redis is unavailable, reducing confusion for users. 
This implementation relies on headers sent by GCDN. If the headers are not present at all, the tests fail gracefully and do not run sit health tests at all.
Included in this implementation is some code that originally was written for [Edge Integrations](https://github.com/pantheon-systems/pantheon-edge-integrations/blob/main/src/HeaderData.php#L38-L73) that allows us to pull the HTTP headers out of the `$_SERVER` superglobal and pluck the value of specific headers. Providing this function in the mu-plugin can be helpful for our future selves or customers building things similar to EI.
Tests have been added to verify this behavior and refine existing …
=> Improve Site Health check for plans without Redis
